### ISSUE TITLE
Replace HTML tags in summary

### ISSUE THREAD

**Issue by foxi69** [plneto/TvMaze.Api.Client#23]
https://api.tvmaze.com/shows/67172

at Summary '&' char is "&amp;"
is it able to fix to remove/repace every html tags?

**Comment by plneto** [comment]
I'm not sure if it would be a good idea to add logic to manipulate this response as the goal of this library is to return the same responses as if you were consuming the API directly.

Can you remove the HTML tags in your own code after you get the response?

**Comment by foxi69** [comment]
> Can you remove the HTML tags in your own code after you get the response?

Yes, i could.

What about these error messages?  can u fix it?

```
Method name : MoveNext
Date : 2023. 03. 01. 20:22:11

Exception type : Flurl.Http.FlurlHttpException
Message : Call failed. An error occurred while sending the request: GET https://api.tvmaze.com/shows/67172/akas
StackTrace :    at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__35.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.Configuration.ThrowExceptionRateLimitingStrategy.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.TvMazeHttpClient.<GetAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MultiUploader.Categories.MovieAndSerieCategory.<GetHungarianTitleFromTvmaze>d__13.MoveNext() in E:\MultiUploader\MultiUploader\Categories\MovieAndSerieCategory.cs:line 776
Exception type : System.Net.Http.HttpRequestException
Message : An error occurred while sending the request.
StackTrace :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 182
Exception type : System.Net.WebException
Message : The underlying connection was closed: An unexpected error occurred on a send.
StackTrace :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Exception type : System.IO.IOException
Message : Authentication failed because the remote party has closed the transport stream.
StackTrace :    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
-----------------------------------------------------------------------------
Method name : MoveNext
Date : 2023. 03. 01. 20:22:12

Exception type : Flurl.Http.FlurlHttpException
Message : Call failed. An error occurred while sending the request: GET https://api.tvmaze.com/shows/67172
StackTrace :    at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__35.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.Configuration.ThrowExceptionRateLimitingStrategy.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.TvMazeHttpClient.<GetAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MultiUploader.Categories.MovieAndSerieCategory.<CheckOtherMovieDatabaseURLAtTvMaze>d__7.MoveNext() in E:\MultiUploader\MultiUploader\Categories\MovieAndSerieCategory.cs:line 521
Exception type : System.Net.Http.HttpRequestException
Message : An error occurred while sending the request.
StackTrace :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext() in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 182
Exception type : System.Net.WebException
Message : The underlying connection was closed: An unexpected error occurred on a send.
StackTrace :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Exception type : System.IO.IOException
Message : Unable to read data from the transport connection: A létező kapcsolatot a távoli állomás kényszerítetten bezárta.
StackTrace :    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
Exception type : System.Net.Sockets.SocketException
Message : A létező kapcsolatot a távoli állomás kényszerítetten bezárta
StackTrace :    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
```

**Comment by plneto** [comment]
I've tried both methods `GetShowAkasAsync` and `GetShowMainInformationAsync` using the show ID `67172` and I didn't get those errors.

Can you please provide the steps to reproduce them?

**Comment by foxi69** [comment]
Sorry, i cant reproduce again this error.

Could be something with tvmaze api idk

**Comment by plneto** [comment]
Thanks for letting me. Feel free to reopen the issue if it happens again.
