### ISSUE TITLE
Flurl.Http.FlurlHttpException

### ISSUE THREAD

**Issue by foxi69** [plneto/TvMaze.Api.Client#25]
Can you return null instead of exception when it happens?

```
Method name : MoveNext
Date : 2024. 02. 15. 14:42:47
 
Exception type : Flurl.Http.FlurlHttpException
Message : Call failed. An error occurred while sending the request: GET https://api.tvmaze.com/lookup/shows?imdb=tt1984119
StackTrace :    at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.Configuration.ThrowExceptionRateLimitingStrategy.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TvMaze.Api.Client.TvMazeHttpClient.<GetAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MultiUploader.Categories.MovieAndSerieCategory.<GetHungarianTitleFromTvmazeAsync>d__17.MoveNext()
Exception type : System.Net.Http.HttpRequestException
Message : An error occurred while sending the request.
StackTrace :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__29.MoveNext()
Exception type : System.Net.WebException
Message : The underlying connection was closed: An unexpected error occurred on a send.
StackTrace :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Exception type : System.IO.IOException
Message : Authentication failed because the remote party has closed the transport stream.
StackTrace :    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
```

**Comment by plneto** [comment]
You can initialize the client with a different behaviour to deal with rate limiting e.g.  `new TvMazeClient(httpClient, new RetryRateLimitingStrategy())`. 

You can also create a custom one in your code to customize the response by implementing the `IRateLimitingStrategy` interface.

**Comment by foxi69** [comment]
Okay, thanks, I'm using this now, but then I'll rewrite it and see!
TvMazeClient tvmazeClient = new TvMazeClient();
